### ISSUE TITLE
Does ROUGE refer to Rouge-L or Rouge-N?

### ISSUE THREAD

**Issue by ogencoglu** [stanfordnlp/string2string#1]
Thanks for the great work!

What does ROUGE metric refer to in your library?

**Comment by suzgunmirac** [comment]
Thanks so much for the encouraging words!

[By default](https://string2string.readthedocs.io/en/latest/metrics.html#rouge), the [`compute` function ](https://github.com/stanfordnlp/string2string/blob/e0d2854fb454d8c1c6009b44b0657d1f39cf55f2/string2string/metrics/rouge.py#L40)in the `ROUGE` class returns the `ROUGE-1`, `ROUGE-2`, `ROUGE-L`, and `ROUGE-LSum` scores in a dictionary.

I hope this answers your question.
